### ISSUE TITLE
[bug] issue with /back

### ISSUE THREAD

**Issue by wolgamir** [fuji-fabric/fuji#283]
### Are you using the latest available version for your server?

- [x] I am using the latest available version of fuji for my minecraft server.

### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Current Behavior

when using /back between 2 positions under ~32 blocks i can get back and forth without a problem but when going over ~32 blocks it looses the last one of them

```
{
  "ignore_distance": 32.0,
  "enable_back_on_death": false,
  "enable_back_on_teleport": true,
  "max_back_location_entries_to_save": 3
}
```

### Expected Behavior

be able to go back and forth under any circumstances

### Anything else?

the ireliabality is quite a concern in my case because im using /back to get back from a creative custom dimension to a survival overworld on the lastNposition, the [dimension mod](https://github.com/DrexHD/WorldManager) im using only offers a tp to spawnpoint of each dimensions.
it will results in people being forced to tp at overworld spawnpoint to get back in the survival world, instead of using /back

**Comment by sakurawald** [comment]
Should be fixed in v6.12.2 version

**Comment by wolgamir** [comment]
will it be possible to implent extra logic by always remembering the `lastNlocation` in `minecraft:overworld` so if we keep tping around in custom dimensions and exceed the number of `savedlocation` we still have a way to get back to the `lastNlocation` in `minecraft:overworld`?

or do you think that increasing the `savedlocation` will do the trick? is there any reason that it is this low by default, like is it for lag/storage?

**Comment by sakurawald** [comment]
> will it be possible to implent extra logic by always remembering the `lastNlocation` in `minecraft:overworld` so if we keep tping around in custom dimensions and exceed the number of `savedlocation` we still have a way to get back to the `lastNlocation` in `minecraft:overworld`?
> 
> or do you think that increasing the `savedlocation` will do the trick? is there any reason that it is this low by default, like is it for lag/storage?

In current implementation, we store records for all dimensions in a list for simplification. The `max_back_location_entries_to_save` option is for all dimensions. Its default value is `3`, you can increase it to a larger value, but there is a possibility to abuse the `/back` command.

The `/back minecraft:overworld` command can teleport you to last location in `minecraft:overworld`, if the target entry is still inside `max_back_location_entries_to_save` option.

**Comment by sakurawald** [comment]
> extra logic by always remembering the `lastNlocation` in `minecraft:overworld`

To make this, we have to maintain a unique list for each dimension, and specify the `max_back_location_entries_to_save` for each dimension. This does increase the complexity of the module, but the use-case is less frequent.

**Comment by sakurawald** [comment]
> or do you think that increasing the `savedlocation` will do the trick? is there any reason that it is this low by default, like is it for lag/storage?

Its default value is low, mainly to prevent the abuse of `/back` command. There is no performance or storage issue for this. If the gameplay of your server allows so, you can increase the value.

**Comment by wolgamir** [comment]
> increase it to a larger value, but there is a possibility to abuse the `/back` command.

ill probably end up doing this, but how so?

**Comment by sakurawald** [comment]
> > increase it to a larger value, but there is a possibility to abuse the `/back` command.
> 
> ill probably end up doing this, but how so?

The default value is `3`, you can increase it to `5` or `10`. It will cover 99% use-case, even for the back and forth use-case.

**Comment by wolgamir** [comment]
oh sorry i was asking how is there a possibility to abuse the `/back` command if value is set to `10 `for example

**Comment by sakurawald** [comment]
> oh sorry i was asking how is there a possibility to abuse the `/back` command if value is set to `10 `for example

A higher value stores more location entries for each player, so there is more useable teleport position to use. And teleport is considered as breaking the vanilla survival. Though you can add a warmup for the teleport command. But by default, the value is only `3` for `/back` command.

**Comment by wolgamir** [comment]
is there a way to write data in `location-history` when a new player join? that way i tell players to only use `/back <dimension>` to access worlds
what is `/back push`?

i was thinking of rewriting the command `/back <dimension>` to `/tpworld <name>` that way players go back to their `last position` in the dimension + i dont have to setup a warp that tp to the spawnpoint of each dimensions, which makes it cleaner i think
if its not possible ill setup wraps

**Comment by sakurawald** [comment]
> is there a way to write data in `location-history` when a new player join? that way i tell players to only use `/back <dimension>` to access worlds what is `/back push`?
> 
> i was thinking of rewriting the command `/back <dimension>` to `/tpworld <name>` that way players go back to their `last position` in the dimension + i dont have to setup a warp that tp to the spawnpoint of each dimensions, which makes it cleaner i think if its not possible ill setup wraps

For normal use-case, you only need to grant the permission to use `/back`. This is the simplest case.
You can also grant the permission to allow the usage of `/back 2` or `/back minecraft:overworld` etc.

The `/back push` is a manual way to push current location into back location history.

There is not way to go to extra dimensions in vanilla Minecraft, so you have to use `teleport mechanism` to go there. The teleport can be provided by `/warp` or some self-created command like `/spawn fuji:overworld`. Setting up a `spawnpoint` for each dimension is recommended, and players can then use `/home` to create their home points in extra dimensions.

**Comment by sakurawald** [comment]
> i was thinking of rewriting the command `/back <dimension>` to `/tpworld <name>` that way players go back to their `last position` in the dimension + i dont have to setup a warp that tp to the spawnpoint of each dimensions

This can be a feature request, to `pin the last one entry for each dimension`, so we always have the last-location information for each dimension.

**Comment by wolgamir** [comment]
> For normal use-case, you only need to grant the permission to use `/back`. This is the simplest case.
> You can also grant the permission to allow the usage of `/back 2` or `/back minecraft:overworld` etc.

about permissions, 
ive set to false `push` `list` and `clear` but they are still showing in the auto completion even if they do not work
